- hosts: websrv
  become: yes

  roles:
    - php-fpm
    - apache-install
    - apache-config
    - sql-local
    - wordpress
    - ssl-self-signed
  vars:
    - mysql_root_password: "asd123456"
    - mysql_db: "wordpress"
    - mysql_user: "sammy"
    - mysql_password: "wppass"
    - http_host: "akoshw.local"
    - http_conf: "akoshw.local.conf"
    - https_conf: "akoshw.local-ssl.conf"
    - php_version: "7.4"
    - php_modules:
        - mysql
        - curl
    - php_fpm_pools:
        - name: blog
          pm_max_children: 10
          pm_start_servers: 4
          pm_min_spare_servers: 2
          pm_max_spare_servers: 6
    - php_fpm_ini_options:
        - {option: post_max_size, value: 100M}
        - {option: upload_max_filesize, value: 100M}
        - {section: opcache, option: opcache.enable, value: 1}
  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
