- hosts: sql_nodes
  become: yes
  
  vars_files:
    - vars/haproxy_defaults.yml
    - vars/mysql_defaults.yml
    - vars/galera_cluster_hosts.yml
  roles:
    - sql-galera

  vars:
    - webserver_private_ip: 10.0.0.100
    - cluster_name: first_cluster
    - private_ips:
       - 10.0.0.201
       - 10.0.0.202
       - 10.0.0.203
