- hosts: websrv
  become: yes

  vars_files:
    - vars/php_defaults.yml
    - vars/wordpress_defaults.yml
    - vars/haproxy_defaults.yml
    - vars/galera_cluster_hosts.yml
  roles:
    - php-fpm
    - apache-install
    - apache-config
    - wordpress
    - ssl-self-signed
    - haproxy
  vars:
    - http_host: "akoshw.local"
    - http_conf: "akoshw.local.conf"
    - https_conf: "akoshw.local-ssl.conf"
