- name: Reload MariaDB
  service:
    name: mariadb
    state: reloaded

- name: Restart MariaDB
  service:
    name: mariadb
    state: restarted

- name: Stop MariaDB
  service:
    name: mariadb
    state: stopped

- name: Start MariaDB
  service:
    name: mariadb
    state: started
