- name: Enable PHP-FPM configuration
  shell: |
   /usr/sbin/a2enconf php{{ php_version }}-fpm
    /usr/sbin/a2enmod proxy
    /usr/sbin/a2enmod proxy_fcgi
  notify: Reload Apache    

- name: Create document root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: '0755'
  tags: [ apache ]

- name: Set up Apache HTTP VirtualHost
  template:
    src: "templates/default.conf.j2"
    dest: "/etc/apache2/sites-available/{{ http_host }}.conf"
  vars:
    pool: "{{ php_fpm_pool_defaults | combine(pool_) }}"
  loop: "{{ php_fpm_pools }}"
  loop_control:
    loop_var: pool_
  notify: Reload Apache
  tags: [ apache ]

- name: Set up Apache HTTPS VirtualHost
  template:
    src: "templates/default-ssl.conf.j2"
    dest: "/etc/apache2/sites-available/{{ http_host }}-ssl.conf"
  vars:
    pool: "{{ php_fpm_pool_defaults | combine(pool_) }}"
  loop: "{{ php_fpm_pools }}"
  loop_control:
    loop_var: pool_
  notify: Reload Apache
  tags: [ apache ]

- name: Enable rewrite module
  shell: /usr/sbin/a2enmod rewrite
  notify: Reload Apache
  tags: [ apache ]

- name: Enable ssl module
  shell: /usr/sbin/a2enmod ssl
  notify: Restart Apache
  tags: [ apache ]

- name: Enable new site
  shell: /usr/sbin/a2ensite {{ http_host }}.conf
  notify: Reload Apache
  tags: [ apache ]

- name: Enable new site
  shell: /usr/sbin/a2ensite {{ http_host }}-ssl.conf
  notify: Reload Apache
  tags: [ apache ]

- name: Disable default Apache site
  shell: /usr/sbin/a2dissite 000-default.conf
  notify: Restart Apache
  tags: [ apache ]
